version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: idelfazletdinov/kittygram_backend:latest
    container_name: django
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: idelfazletdinov/kittygram_frontend:latest
    container_name: react
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: idelfazletdinov/kittygram_gateway:latest
    container_name: nginx
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media